### ISSUE TITLE
pushing only the message of an error in meta.promise/err makes errors hard to debug

### ISSUE THREAD

**Issue by thedavidmeister** [degree9/meta#22]
Lots of useful info gets thrown away, making promises harder to debug than necessary.

compare:

<img width="693" alt="localhost_8080___login_and_new_issue_ _degree9_meta" src="https://user-images.githubusercontent.com/629710/37595759-141f166e-2bce-11e8-8550-037ff467bbb7.png">
<img width="648" alt="localhost_8080___login" src="https://user-images.githubusercontent.com/629710/37595804-35665ed6-2bce-11e8-8fc0-df6804a3e5ad.png">

**Comment by thedavidmeister** [comment]
```
   (prom/catch
    (fn [err]
     (.error js/console (.-message err) err))))))
```

**Comment by benjamingr** [comment]
Hey, asking for Node.js - why are promises harder to debug here? Is there anything we can do to have a better promises story for people transpiling clojure/cjs to Node?

**Comment by flyboarder** [comment]
@benjamingr are you asking about this library specifically? I find the debugging process is fairly straight forward with promises. Simply catch and prn at the top most level and use pretty errors deeper down.
