### ISSUE TITLE
should be possible to add hooks to the entire app, not just per-path

### ISSUE THREAD

**Issue by thedavidmeister** [degree9/meta#25]
Not sure if this should be here or in https://github.com/degree9/featherscript but currently there only seems to be a way to add hooks per api endpoint as per `meta.server/api`.

Feathers itself allows for app-wide hooks, such as this example to ensure valid JWTs are always present:

```clojure
(defn with-always-enforce-valid-jwt
 [app]
 (let [auth (:authenticate feathers.authentication/hooks)
       jwt-hook (auth. "jwt")]
  (.hooks app (clj->js {:before {:all [jwt-hook]}}))))
```

**Comment by flyboarder** [comment]
Moving this request to degree9/featherscript#6
