### ISSUE TITLE
Invalid LOC header (bad signature) ...feathers/client.cljs

### ISSUE THREAD

**Issue by DVious** [degree9/meta#30]
Hi,

I am trying to install meta in Mac High Sierra - an 8gb laptop.

I cannot get past the --develop error:
'Compiling ClojureScript...
• index.html.js
• nodejs.js
**ZipFile invalid LOC header (bad signature) at line 1, column 1 in file jar:file:/...featherscript-0.4.0-SNAPSHOT.jar!/feathers/client.cljs**
Elapsed time: 18.643 sec'

I read of an issue with the OS X build of zipfile and, so, I installed Unzip, using brew.  I don't think I did enough to replace the, flaky, OS X version, if that is the issue.

I ran unzip against featherscript-0.4.0-SNAPSHOT.jar.  The same 'feathers' folder appears to be produced, before the LOC header error. 

Earlier, this evening, I managed to successfully install beakerx from scratch, and without Docker.  I just know I can get meta fired up, in the next 24 hours!

**Comment by flyboarder** [comment]
I pushed a new version of `featherscript-0.4.0-SNAPSHOT`. Could you try again and let me know if this is happening to the latest version?

**Comment by DVious** [comment]
I'd previously deleted .m2/ so, --develop pulls ****'featherscript-0.4.0-20180707.004625-127.jar'****.

**Comment by flyboarder** [comment]
I cannot seem to reproduce this locally, I would imagine this is being caused by something on your system.

**Comment by DVious** [comment]
Thanks for trying but, I'm running out of dev machines to swap to!

Reckon I'll step through the meta code and see if I can do, manually, what the code was trying to automate.  Evade featherscript, somehow?!

My 24 hours target was always optimistic!

**Comment by DVious** [comment]
This issue appears to have gone away - now I'm back to the Sigbus error!

**Comment by flyboarder** [comment]
can you post your build.boot file

**Comment by DVious** [comment]
I haven't got one, beyond the build.boot that is generated in the app folder, as per the (for the fearless) instructions.

I took it that, by building the generated app, I would have minimal meta framework running in a real - I've made no changes to any cloned files.

**Comment by DVious** [comment]
Actually - the install I run always looks for 0.4.0-SNAPSHOT, and even finds several jars.

Now that I force for that version, and generate the app from within /usr/local/meta, I get some progress:

Initial Project Version...: 0.2.0
Running Workflow...: develop
Syncing git repository with: origin/master
Current Build Version...: 0.2.0-SNAPSHOT
Adding file to fileset... 
• ./package.json -> ./package.json 
Writing property file .npmrc...
Executing Process: /usr/local/bin/npm
npm WARN saveError ENOENT: no such file or directory, open '/Users/../.boot/cache/cache/project/usr/local/meta/feathers.boot-feathers/feathers/package.json'

The Initial Project Version is progress, as it was previously at 0.0.0.  

A whole string of packages does not exist in feathers - a package that previously gave me errors.

It all ends with a message:
 
'Generating EDN file...
• nodejs.cljs.edn
Compiling ClojureScript...
• index.html.js
• nodejs.jsNo such namespace: uikit, could not locate uikit.cljs..'
