### ISSUE TITLE
Unable to setup project

### ISSUE THREAD

**Issue by nisargjoshi95** [degree9/meta#42]
Hi, I'm new to clojure and its tools so I'm not sure where to start with this error. I've managed to set up a hoplon project and its working well. Now I'm trying to set up meta, but when I run the `boot -d degree9/meta generate --name meta-starter` command I see this error: 

`Retrieving maven-metadata.xml from https://repo.clojars.org/
Retrieving maven-metadata.xml from https://repo.clojars.org/
Classpath conflict: org.clojure/clojure version 1.10.0 already loaded, NOT loading version 1.9.0
WARNING: compile already refers to: #'clojure.core/compile in namespace: boot.user, being replaced by: #'meta.boot/compile
                              java.lang.Thread.run              Thread.java:  748
java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  624
 java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1149
               java.util.concurrent.FutureTask.run          FutureTask.java:  266
                                               ...                               
               clojure.core/binding-conveyor-fn/fn                 core.clj: 2030
                                 boot.core/boot/fn                 core.clj: 1033
                                               ...                               
                         boot.core/construct-tasks                 core.clj:  973
                         boot.core/construct-tasks                 core.clj:  991
java.lang.IllegalArgumentException: Unknown option: "--name"
        clojure.lang.ExceptionInfo: Unknown option: "--name"
    line: 3
`

**Comment by flyboarder** [comment]
The generator is not the best way to currently use the project as it's under heavy development
